### ISSUE TITLE
median not working in avg

### ISSUE THREAD

**Issue by b-v** [adamhotep/misc-scripts#1]
The `avg` utility is very useful. However, the median function does not always give the correct result. For example if there is only one number, say 1, the median should give 1. The current implementation returns 0.5 instead. The result for two numbers, say 1 and 2, is 2 instead of 1.5.

**Comment by adamhotep** [comment]
Thanks for pointing that out, @b-v. I'm happy to see somebody using my scripts!

This is fixed now, please reopen if you still experience this bug (or if my fix created a new one).

**Comment by b-v** [comment]
Thanks @adamhotep. Unfortunately it still doesn't work. For an odd number of items it should return the middle and for an even the average of the middle two (see, e.g., [here](https://en.wikipedia.org/wiki/Median#/media/File:Finding_the_median.png)). Currently for the numbers 2, 2 and 3 it returns 2.5 instead of 2 and for 2, 2, 3 and 3 it returns 3 instead of 2.5.

**Comment by adamhotep** [comment]
I found the issue. It was an off-by-one error in my original code. My last fix merely fixed the answer for one or two inputs. It should work now (and it also now calculates the mode).
